<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://yuiko/soa"
           targetNamespace="http://yuiko/soa" elementFormDefault="qualified">

    <!-- example -->

    <xs:element name="getCountryRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="getCountryResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="country" type="tns:country"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="country">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="population" type="xs:int"/>
            <xs:element name="capital" type="xs:string"/>
            <xs:element name="currency" type="tns:currency"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="currency">
        <xs:restriction base="xs:string">
            <xs:enumeration value="GBP"/>
            <xs:enumeration value="EUR"/>
            <xs:enumeration value="PLN"/>
        </xs:restriction>
    </xs:simpleType>


    <!-- genocide -->
    <xs:element name="pingRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="status" type="xs:string" default="OK"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="pingResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="result" type="xs:string" default="OK"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="deportRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id-from" type="xs:long"/>
                <xs:element name="id-to" type="xs:long"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="deportResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="deported" type="xs:long"/>
                <xs:element name="result" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="killRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:long"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="killResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="killed" type="xs:long"/>
                <xs:element name="result" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>