version: '3.8'

services:
  genocide-service:
    build: ./genocide
    container_name: genocide-service
    networks:
      - backend 
    depends_on:
      - main-db
    ports:
      - "4949:4848"
      - "8282:8080"
      - "8383:8181"

  soa-service:
    build: ./soa
    container_name: soa-service
    networks:
      - backend
    depends_on:
      - main-db
    ports:
      - "4040:4848"
      - "7070:8080"
      - "7171:8181"

  main-db:
    image: postgres
    container_name: main-db
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    command: postgres -p 5432
    networks:
      - backend
    ports:
      - "5432:5432"

networks:
  backend:
    driver: bridge